# Generated by Django 6.0.1 on 2026-01-27 04:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_department'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('running', 'Running'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('target_contacts_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('target_filter', models.JSONField(blank=True, default=dict)),
                ('message_template_id', models.UUIDField(blank=True, null=True)),
                ('message_content', models.TextField()),
                ('message_variables', models.JSONField(blank=True, default=dict)),
                ('sent_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivered_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('read_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('failed_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='organizations.organization')),
                ('whatsapp_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaigns', to='whatsapp.whatsappnumber')),
            ],
            options={
                'db_table': 'campaigns',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='campaigns_organiz_0c0cd6_idx'), models.Index(fields=['scheduled_at'], name='campaigns_schedul_e9d492_idx')],
            },
        ),
    ]
