[package]
name = "simple_api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true }
actix-cors = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
jsonwebtoken = "9.2"
sea-orm = { workspace = true }
dotenvy = { workspace = true }
log = "0.4"
actix-ws = { workspace = true }
futures-util = "0.3"
reqwest = { version = "0.11", features = ["json"] }
