services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: pytake-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: pytake
      POSTGRES_PASSWORD: pytake_dev
      POSTGRES_DB: pytake
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pytake"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: pytake-backend
    restart: unless-stopped
    environment:
      DATABASE_URL: postgres://pytake:pytake_dev@postgres:5432/pytake
      JWT_SECRET: development_jwt_secret
      RUST_LOG: info,simple_api=debug
      WHATSAPP_PHONE_NUMBER_ID: 574293335763643
      WHATSAPP_ACCESS_TOKEN: EAAJLLK95RIUBPBFCKmWgvUZAZBNd9bvwpSBiOWpriLG0R7xmb1EM06ShsZBEQsvgrCkchP3Uv7eWXAwilky4GLEe47zvdz5GEUTAwF3BonBthdOZBA1bXPo5K6RKTJx3gJAOIWUq9FfJVPAZCwpKKge4jUMjQO74F6ikDxnBrFwyKBcdCE5FccHCRh8gHu0OIYhUe0fErLCE7vjOqVPBUsHQxmmpzwC8RzMmGBb8iG1gFZBidxyu76bZClsAQZDZD
      WHATSAPP_WEBHOOK_VERIFY_TOKEN: verify_token_123
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: