[package]
name = "pytake-simple-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "simple_server"
path = "simple_server.rs"

[dependencies]
actix-web = "4.5"
actix-cors = "0.7"
serde_json = "1.0"
tokio = { version = "1.37", features = ["full"] }
chrono = { version = "0.4", features = ["serde"] }
env_logger = "0.11"