# Generated by Django 6.0.1 on 2026-01-27 04:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='AICustomModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=255)),
                ('provider', models.CharField(max_length=50)),
                ('model_id', models.CharField(max_length=255)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_models', to='organizations.organization')),
            ],
            options={
                'db_table': 'ai_custom_models',
                'ordering': ['-created_at'],
            },
        ),
    ]
