# Generated by Django 6.0.2 on 2026-02-10 02:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0001_initial"),
        ("organizations", "0002_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="AISettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Timestamp when record was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp when record was last updated",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        help_text="Timestamp when record was soft deleted",
                        null=True,
                    ),
                ),
                ("enabled", models.BooleanField(default=True)),
                ("provider", models.CharField(default="openai", max_length=50)),
                ("model", models.CharField(default="gpt-4", max_length=100)),
                ("temperature", models.FloatField(default=0.7)),
                ("max_tokens", models.IntegerField(default=1000)),
                ("features", models.JSONField(blank=True, default=dict)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_settings",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Setting",
                "verbose_name_plural": "AI Settings",
                "db_table": "ai_settings",
            },
        ),
    ]
