# Generated by Django 6.0.2 on 2026-02-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_assistant", "0002_aisettings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aisettings",
            name="features",
        ),
        migrations.AddField(
            model_name="aisettings",
            name="anthropic_api_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="enable_flow_generation",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="enable_improvements",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="gemini_api_key",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="aisettings",
            name="openai_api_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
