# Generated by Django 6.0.1 on 2026-01-27 04:43

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbots', '0001_initial'),
        ('organizations', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppNumber',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('connection_type', models.CharField(choices=[('official', 'Official Meta API'), ('qrcode', 'QR Code (Evolution API)')], default='official', max_length=20)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('display_name', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('profile_picture_url', models.URLField(blank=True, max_length=500, null=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_business_account_id', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('app_secret', models.TextField(blank=True, null=True)),
                ('webhook_verify_token', models.CharField(blank=True, max_length=255, null=True)),
                ('evolution_instance_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('evolution_api_url', models.URLField(blank=True, max_length=500, null=True)),
                ('evolution_api_key', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error')], default='disconnected', max_length=20)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('quality_rating', models.CharField(blank=True, max_length=50, null=True)),
                ('messaging_limit_tier', models.CharField(blank=True, max_length=50, null=True)),
                ('business_hours', models.JSONField(blank=True, default=dict)),
                ('away_message', models.TextField(blank=True, null=True)),
                ('welcome_message', models.TextField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('webhook_url', models.URLField(blank=True, max_length=500, null=True)),
                ('webhook_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('default_chatbot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='chatbots.chatbot')),
                ('default_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_numbers', to='organizations.organization')),
            ],
            options={
                'db_table': 'whatsapp_numbers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('language', models.CharField(default='pt_BR', max_length=10)),
                ('category', models.CharField(choices=[('MARKETING', 'Marketing'), ('UTILITY', 'Utility'), ('AUTHENTICATION', 'Authentication')], max_length=50)),
                ('suggested_category', models.CharField(blank=True, max_length=50, null=True)),
                ('meta_template_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISABLED', 'Disabled'), ('DELETED', 'Deleted')], db_index=True, default='DRAFT', max_length=50)),
                ('rejected_reason', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('ai_analysis_result', models.JSONField(blank=True, null=True)),
                ('ai_analysis_score', models.FloatField(blank=True, null=True)),
                ('ai_suggested_category', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('header_type', models.CharField(blank=True, max_length=50, null=True)),
                ('header_text', models.TextField(blank=True, null=True)),
                ('header_variables_count', models.IntegerField(default=0)),
                ('body_text', models.TextField()),
                ('body_variables_count', models.IntegerField(default=0)),
                ('footer_text', models.TextField(blank=True, null=True)),
                ('buttons', models.JSONField(blank=True, default=list)),
                ('variables', models.JSONField(blank=True, default=list)),
                ('parameter_format', models.CharField(choices=[('POSITIONAL', 'Positional'), ('NAMED', 'Named')], default='POSITIONAL', max_length=20)),
                ('named_variables', models.JSONField(blank=True, default=list)),
                ('quality_score', models.CharField(blank=True, max_length=20, null=True)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_at', models.DateTimeField(blank=True, null=True)),
                ('disabled_reason', models.TextField(blank=True, null=True)),
                ('last_status_update', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('delivered_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('read_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('failed_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_system_template', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_templates', to='organizations.organization')),
                ('whatsapp_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='whatsapp.whatsappnumber')),
            ],
            options={
                'db_table': 'whatsapp_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='whatsappnumber',
            index=models.Index(fields=['organization', 'phone_number'], name='whatsapp_nu_organiz_db5c99_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsappnumber',
            index=models.Index(fields=['status'], name='whatsapp_nu_status_0a17a4_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['organization', 'name'], name='whatsapp_te_organiz_7f91e4_idx'),
        ),
        migrations.AddIndex(
            model_name='whatsapptemplate',
            index=models.Index(fields=['status'], name='whatsapp_te_status_7920c7_idx'),
        ),
    ]
