# Generated by Django 6.0.1 on 2026-01-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("whatsapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="whatsappnumber",
            name="webhook_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="Unique webhook identifier for Meta verification",
                null=True,
            ),
        ),
    ]
