"""Add UUID default to chatbot_number_links id

Revision ID: 5d648988529a
Revises: 20251211_001_flow_multi_binding
Create Date: 2025-12-12 01:15:53.780306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d648988529a'
down_revision: Union[str, None] = '20251211_001_flow_multi_binding'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_skills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_name', sa.String(length=100), nullable=False),
    sa.Column('proficiency_level', sa.Integer(), server_default='3', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_skills_created_at'), 'agent_skills', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_skills_deleted_at'), 'agent_skills', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_agent_skills_organization_id'), 'agent_skills', ['organization_id'], unique=False)
    op.create_index(op.f('ix_agent_skills_skill_name'), 'agent_skills', ['skill_name'], unique=False)
    op.create_index(op.f('ix_agent_skills_user_id'), 'agent_skills', ['user_id'], unique=False)
    op.alter_column('chatbot_linking_history', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('chatbot_linking_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('chatbot_linking_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_chatbot_linking_history_timestamp'), table_name='chatbot_linking_history')
    op.create_index(op.f('ix_chatbot_linking_history_created_at'), 'chatbot_linking_history', ['created_at'], unique=False)
    op.alter_column('chatbot_number_links', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.alter_column('chatbot_number_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('chatbot_number_links', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_chatbot_number_links_created_at'), 'chatbot_number_links', ['created_at'], unique=False)
    op.drop_index(op.f('ix_chatbots_whatsapp_number_id'), table_name='chatbots')
    op.drop_constraint(op.f('fk_chatbots_whatsapp_number_id'), 'chatbots', type_='foreignkey')
    op.drop_column('chatbots', 'whatsapp_number_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbots', sa.Column('whatsapp_number_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_chatbots_whatsapp_number_id'), 'chatbots', 'whatsapp_numbers', ['whatsapp_number_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_chatbots_whatsapp_number_id'), 'chatbots', ['whatsapp_number_id'], unique=False)
    op.drop_index(op.f('ix_chatbot_number_links_created_at'), table_name='chatbot_number_links')
    op.alter_column('chatbot_number_links', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chatbot_number_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chatbot_number_links', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_chatbot_linking_history_created_at'), table_name='chatbot_linking_history')
    op.create_index(op.f('ix_chatbot_linking_history_timestamp'), 'chatbot_linking_history', ['timestamp'], unique=False)
    op.alter_column('chatbot_linking_history', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chatbot_linking_history', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('chatbot_linking_history', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_agent_skills_user_id'), table_name='agent_skills')
    op.drop_index(op.f('ix_agent_skills_skill_name'), table_name='agent_skills')
    op.drop_index(op.f('ix_agent_skills_organization_id'), table_name='agent_skills')
    op.drop_index(op.f('ix_agent_skills_deleted_at'), table_name='agent_skills')
    op.drop_index(op.f('ix_agent_skills_created_at'), table_name='agent_skills')
    op.drop_table('agent_skills')
    # ### end Alembic commands ###
