# Generated by Django 6.0.1 on 2026-01-27 04:43

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatbots', '0001_initial'),
        ('organizations', '0002_department'),
        ('queues', '0001_initial'),
        ('whatsapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('whatsapp_id', models.CharField(db_index=True, max_length=20)),
                ('whatsapp_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar_url', models.URLField(blank=True, max_length=500, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('address_street', models.CharField(blank=True, max_length=255, null=True)),
                ('address_city', models.CharField(blank=True, max_length=100, null=True)),
                ('address_state', models.CharField(blank=True, max_length=100, null=True)),
                ('address_country', models.CharField(blank=True, max_length=100, null=True)),
                ('address_zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('lead_score', models.IntegerField(default=0)),
                ('lifecycle_stage', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('opt_in', models.BooleanField(default=True)),
                ('opt_in_date', models.DateTimeField(blank=True, null=True)),
                ('opt_out_date', models.DateTimeField(blank=True, null=True)),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_reason', models.TextField(blank=True, null=True)),
                ('is_vip', models.BooleanField(db_index=True, default=False)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_message_received_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_sent_at', models.DateTimeField(blank=True, null=True)),
                ('total_messages_sent', models.IntegerField(default=0)),
                ('total_messages_received', models.IntegerField(default=0)),
                ('total_conversations', models.IntegerField(default=0)),
                ('average_response_time_seconds', models.IntegerField(blank=True, null=True)),
                ('last_engagement_score', models.IntegerField(default=0)),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_contacts', to=settings.AUTH_USER_MODEL)),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='organizations.organization')),
            ],
            options={
                'db_table': 'contacts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_customer_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_agent_message_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('is_unread', models.BooleanField(db_index=True, default=True)),
                ('is_priority', models.BooleanField(db_index=True, default=False)),
                ('is_spam', models.BooleanField(default=False)),
                ('message_count', models.IntegerField(default=0)),
                ('agent_message_count', models.IntegerField(default=0)),
                ('customer_message_count', models.IntegerField(default=0)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('active_chatbot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_conversations', to='chatbots.chatbot')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='conversations.contact')),
                ('current_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_conversations', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='organizations.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='organizations.organization')),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='queues.queue')),
                ('whatsapp_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='whatsapp.whatsappnumber')),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('event_data', models.JSONField(blank=True, default=dict)),
                ('message', models.TextField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='conversations.conversation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'conversation_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('current_node_id', models.UUIDField(blank=True, null=True)),
                ('variables', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('last_interaction_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='conversations.conversation')),
            ],
            options={
                'db_table': 'conversation_states',
            },
        ),
        migrations.CreateModel(
            name='ConversationWindow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('opened_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('messages_sent', models.IntegerField(default=0)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='conversations.conversation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_windows', to='organizations.organization')),
                ('whatsapp_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_windows', to='whatsapp.whatsappnumber')),
            ],
            options={
                'db_table': 'conversation_windows',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['organization', 'whatsapp_id'], name='contacts_organiz_63e6ea_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['is_vip'], name='contacts_is_vip_531f05_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together={('organization', 'whatsapp_id')},
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['organization', 'status'], name='conversatio_organiz_fb54ab_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['contact', '-last_message_at'], name='conversatio_contact_b2fc18_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['current_agent', 'status'], name='conversatio_current_d82649_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_message_at'], name='conversatio_last_me_99c95c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationwindow',
            index=models.Index(fields=['conversation', 'is_active'], name='conversatio_convers_b492d1_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationwindow',
            index=models.Index(fields=['expires_at'], name='conversatio_expires_9627e9_idx'),
        ),
    ]
