# Generated by Django 6.0.1 on 2026-01-27 04:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chatbot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatbots', to='organizations.organization')),
            ],
            options={
                'db_table': 'chatbots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlowAutomation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=255)),
                ('trigger_type', models.CharField(max_length=50)),
                ('trigger_config', models.JSONField(blank=True, default=dict)),
                ('actions', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('chatbot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to='chatbots.chatbot')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flow_automations', to='organizations.organization')),
            ],
            options={
                'db_table': 'flow_automations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='chatbot',
            index=models.Index(fields=['organization', 'is_active'], name='chatbots_organiz_608594_idx'),
        ),
    ]
