# Generated by Django 6.0.1 on 2026-01-27 04:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('permissions', models.JSONField(blank=True, default=list)),
                ('is_system_role', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(blank=True, help_text='Organization this role belongs to (null for system roles)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization')),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['organization', 'slug'], name='roles_organiz_796681_idx'), models.Index(fields=['is_system_role'], name='roles_is_syst_135658_idx')],
                'unique_together': {('organization', 'slug')},
            },
        ),
    ]
