version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: pytake_postgres
    environment:
      POSTGRES_USER: pytake
      POSTGRES_PASSWORD: pytake123
      POSTGRES_DB: pytake_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pytake"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: pytake_redis
    command: redis-server --requirepass pytake123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "auth", "pytake123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: pytake_adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data: