"""initial_migration

Revision ID: 0153cb050e63
Revises: 
Create Date: 2025-10-03 15:34:52.491152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0153cb050e63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('whatsapp_business_id', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_webhook_verify_token', sa.String(length=255), nullable=True),
    sa.Column('plan_type', sa.String(length=50), server_default='free', nullable=False),
    sa.Column('plan_starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('plan_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_chatbots', sa.Integer(), nullable=True),
    sa.Column('max_whatsapp_numbers', sa.Integer(), nullable=True),
    sa.Column('max_contacts', sa.Integer(), nullable=True),
    sa.Column('max_agents', sa.Integer(), nullable=True),
    sa.Column('max_departments', sa.Integer(), nullable=True),
    sa.Column('monthly_message_limit', sa.Integer(), nullable=True),
    sa.Column('current_chatbots_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('current_whatsapp_numbers_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('current_contacts_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('current_agents_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('current_month_messages_sent', sa.Integer(), server_default='0', nullable=True),
    sa.Column('current_month_messages_received', sa.Integer(), server_default='0', nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_trial', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_index(op.f('ix_organizations_created_at'), 'organizations', ['created_at'], unique=False)
    op.create_index(op.f('ix_organizations_deleted_at'), 'organizations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_organizations_plan_type'), 'organizations', ['plan_type'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('chatbots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('global_variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('total_conversations', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_messages_sent', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_messages_received', sa.Integer(), server_default='0', nullable=True),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('published_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chatbots_created_at'), 'chatbots', ['created_at'], unique=False)
    op.create_index(op.f('ix_chatbots_deleted_at'), 'chatbots', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_chatbots_organization_id'), 'chatbots', ['organization_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), server_default='#3B82F6', nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('business_hours', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('offline_message', sa.Text(), nullable=True),
    sa.Column('routing_mode', sa.String(length=50), server_default='round_robin', nullable=False),
    sa.Column('auto_assign_conversations', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('max_conversations_per_agent', sa.Integer(), server_default='10', nullable=True),
    sa.Column('agent_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text('ARRAY[]::uuid[]'), nullable=False),
    sa.Column('total_agents', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_conversations', sa.Integer(), server_default='0', nullable=True),
    sa.Column('active_conversations', sa.Integer(), server_default='0', nullable=True),
    sa.Column('queued_conversations', sa.Integer(), server_default='0', nullable=True),
    sa.Column('average_response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('average_resolution_time_seconds', sa.Integer(), nullable=True),
    sa.Column('customer_satisfaction_score', sa.Integer(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_created_at'), 'departments', ['created_at'], unique=False)
    op.create_index(op.f('ix_departments_deleted_at'), 'departments', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    op.create_index(op.f('ix_departments_organization_id'), 'departments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_departments_slug'), 'departments', ['slug'], unique=False)
    op.create_table('tags',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=7), server_default='#3B82F6', nullable=True),
    sa.Column('is_system', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('contacts_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_created_at'), 'tags', ['created_at'], unique=False)
    op.create_index(op.f('ix_tags_name'), 'tags', ['name'], unique=False)
    op.create_index(op.f('ix_tags_organization_id'), 'tags', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=50), server_default='agent', nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), server_default=sa.text('ARRAY[]::varchar[]'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_online', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', postgresql.INET(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reset_password_token', sa.String(length=255), nullable=True),
    sa.Column('reset_password_expires', sa.DateTime(timezone=True), nullable=True),
    sa.Column('department_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text('ARRAY[]::uuid[]'), nullable=False),
    sa.Column('agent_status', sa.String(length=50), nullable=True),
    sa.Column('agent_greeting_message', sa.Text(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_id', sa.String(length=20), nullable=False),
    sa.Column('whatsapp_name', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_state', sa.String(length=100), nullable=True),
    sa.Column('address_country', sa.String(length=100), nullable=True),
    sa.Column('address_zipcode', sa.String(length=20), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('lead_score', sa.Integer(), server_default='0', nullable=True),
    sa.Column('lifecycle_stage', sa.String(length=50), nullable=True),
    sa.Column('opt_in', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('opt_in_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opt_out_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_messages_sent', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_messages_received', sa.Integer(), server_default='0', nullable=True),
    sa.Column('total_conversations', sa.Integer(), server_default='0', nullable=True),
    sa.Column('average_response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('last_engagement_score', sa.Integer(), server_default='0', nullable=True),
    sa.Column('assigned_agent_id', sa.UUID(), nullable=True),
    sa.Column('assigned_department_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_assigned_agent_id'), 'contacts', ['assigned_agent_id'], unique=False)
    op.create_index(op.f('ix_contacts_assigned_department_id'), 'contacts', ['assigned_department_id'], unique=False)
    op.create_index(op.f('ix_contacts_created_at'), 'contacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_contacts_deleted_at'), 'contacts', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_last_message_at'), 'contacts', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_contacts_lifecycle_stage'), 'contacts', ['lifecycle_stage'], unique=False)
    op.create_index(op.f('ix_contacts_name'), 'contacts', ['name'], unique=False)
    op.create_index(op.f('ix_contacts_organization_id'), 'contacts', ['organization_id'], unique=False)
    op.create_index(op.f('ix_contacts_source'), 'contacts', ['source'], unique=False)
    op.create_index(op.f('ix_contacts_whatsapp_id'), 'contacts', ['whatsapp_id'], unique=False)
    op.create_table('flows',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('chatbot_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_main', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_fallback', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('canvas_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text('\'{"nodes": [], "edges": []}\'::jsonb'), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chatbot_id'], ['chatbots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flows_chatbot_id'), 'flows', ['chatbot_id'], unique=False)
    op.create_index(op.f('ix_flows_created_at'), 'flows', ['created_at'], unique=False)
    op.create_index(op.f('ix_flows_deleted_at'), 'flows', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_flows_organization_id'), 'flows', ['organization_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_created_at'), 'refresh_tokens', ['created_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('whatsapp_numbers',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('phone_number_id', sa.String(length=255), nullable=False),
    sa.Column('whatsapp_business_account_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('profile_picture_url', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('webhook_verify_token', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_rating', sa.String(length=50), nullable=True),
    sa.Column('messaging_limit_tier', sa.String(length=50), nullable=True),
    sa.Column('default_chatbot_id', sa.UUID(), nullable=True),
    sa.Column('default_department_id', sa.UUID(), nullable=True),
    sa.Column('business_hours', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('away_message', sa.Text(), nullable=True),
    sa.Column('welcome_message', sa.Text(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['default_chatbot_id'], ['chatbots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['default_department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number_id')
    )
    op.create_index(op.f('ix_whatsapp_numbers_created_at'), 'whatsapp_numbers', ['created_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_numbers_deleted_at'), 'whatsapp_numbers', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_numbers_organization_id'), 'whatsapp_numbers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_numbers_phone_number'), 'whatsapp_numbers', ['phone_number'], unique=False)
    op.create_table('contact_tags',
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('contact_id', 'tag_id')
    )
    op.create_table('nodes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('flow_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('position_x', sa.Integer(), server_default='0', nullable=True),
    sa.Column('position_y', sa.Integer(), server_default='0', nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nodes_created_at'), 'nodes', ['created_at'], unique=False)
    op.create_index(op.f('ix_nodes_flow_id'), 'nodes', ['flow_id'], unique=False)
    op.create_index(op.f('ix_nodes_node_id'), 'nodes', ['node_id'], unique=False)
    op.create_index(op.f('ix_nodes_node_type'), 'nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_nodes_organization_id'), 'nodes', ['organization_id'], unique=False)
    op.create_table('whatsapp_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_number_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('meta_template_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='DRAFT', nullable=False),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('header_type', sa.String(length=50), nullable=True),
    sa.Column('header_text', sa.Text(), nullable=True),
    sa.Column('header_variables_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_variables_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('footer_text', sa.Text(), nullable=True),
    sa.Column('buttons', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('sent_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('delivered_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('read_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('failed_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('is_system_template', sa.Boolean(), server_default='false', nullable=True),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whatsapp_number_id'], ['whatsapp_numbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whatsapp_templates_created_at'), 'whatsapp_templates', ['created_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_deleted_at'), 'whatsapp_templates', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_name'), 'whatsapp_templates', ['name'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_organization_id'), 'whatsapp_templates', ['organization_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_status'), 'whatsapp_templates', ['status'], unique=False)
    op.create_index(op.f('ix_whatsapp_templates_whatsapp_number_id'), 'whatsapp_templates', ['whatsapp_number_id'], unique=False)
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('whatsapp_number_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.String(length=50), server_default='broadcast', nullable=False),
    sa.Column('status', sa.String(length=50), server_default='draft', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('message_content', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('template_variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('audience_type', sa.String(length=50), server_default='all_contacts', nullable=False),
    sa.Column('target_tag_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text('ARRAY[]::uuid[]'), nullable=False),
    sa.Column('target_contact_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text('ARRAY[]::uuid[]'), nullable=False),
    sa.Column('segment_filters', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('messages_per_hour', sa.Integer(), server_default='100', nullable=True),
    sa.Column('delay_between_messages_seconds', sa.Integer(), server_default='2', nullable=True),
    sa.Column('respect_opt_out', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('skip_active_conversations', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('total_recipients', sa.Integer(), server_default='0', nullable=True),
    sa.Column('messages_sent', sa.Integer(), server_default='0', nullable=True),
    sa.Column('messages_delivered', sa.Integer(), server_default='0', nullable=True),
    sa.Column('messages_read', sa.Integer(), server_default='0', nullable=True),
    sa.Column('messages_failed', sa.Integer(), server_default='0', nullable=True),
    sa.Column('messages_pending', sa.Integer(), server_default='0', nullable=True),
    sa.Column('replies_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('unique_replies_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('opt_outs_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('delivery_rate', sa.Float(), nullable=True),
    sa.Column('read_rate', sa.Float(), nullable=True),
    sa.Column('reply_rate', sa.Float(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('error_count', sa.Integer(), server_default='0', nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['whatsapp_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['whatsapp_number_id'], ['whatsapp_numbers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_campaign_type'), 'campaigns', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_campaigns_created_at'), 'campaigns', ['created_at'], unique=False)
    op.create_index(op.f('ix_campaigns_created_by_user_id'), 'campaigns', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_campaigns_deleted_at'), 'campaigns', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_campaigns_name'), 'campaigns', ['name'], unique=False)
    op.create_index(op.f('ix_campaigns_organization_id'), 'campaigns', ['organization_id'], unique=False)
    op.create_index(op.f('ix_campaigns_scheduled_at'), 'campaigns', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_campaigns_template_id'), 'campaigns', ['template_id'], unique=False)
    op.create_index(op.f('ix_campaigns_whatsapp_number_id'), 'campaigns', ['whatsapp_number_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('contact_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_number_id', sa.UUID(), nullable=True),
    sa.Column('current_agent_id', sa.UUID(), nullable=True),
    sa.Column('department_id', sa.UUID(), nullable=True),
    sa.Column('active_chatbot_id', sa.UUID(), nullable=True),
    sa.Column('active_flow_id', sa.UUID(), nullable=True),
    sa.Column('current_node_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='open', nullable=False),
    sa.Column('channel', sa.String(length=50), server_default='whatsapp', nullable=False),
    sa.Column('is_bot_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_human_requested', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('handoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('queue_priority', sa.Integer(), server_default='0', nullable=True),
    sa.Column('first_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_from_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_message_from_agent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_inbound_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('window_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_messages', sa.Integer(), server_default='0', nullable=True),
    sa.Column('messages_from_contact', sa.Integer(), server_default='0', nullable=True),
    sa.Column('messages_from_agent', sa.Integer(), server_default='0', nullable=True),
    sa.Column('messages_from_bot', sa.Integer(), server_default='0', nullable=True),
    sa.Column('first_response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('average_response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('context_variables', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('rating_comment', sa.Text(), nullable=True),
    sa.Column('rated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['active_chatbot_id'], ['chatbots.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['active_flow_id'], ['flows.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_agent_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['current_node_id'], ['nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['whatsapp_number_id'], ['whatsapp_numbers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_active_chatbot_id'), 'conversations', ['active_chatbot_id'], unique=False)
    op.create_index(op.f('ix_conversations_channel'), 'conversations', ['channel'], unique=False)
    op.create_index(op.f('ix_conversations_contact_id'), 'conversations', ['contact_id'], unique=False)
    op.create_index(op.f('ix_conversations_created_at'), 'conversations', ['created_at'], unique=False)
    op.create_index(op.f('ix_conversations_current_agent_id'), 'conversations', ['current_agent_id'], unique=False)
    op.create_index(op.f('ix_conversations_deleted_at'), 'conversations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_conversations_department_id'), 'conversations', ['department_id'], unique=False)
    op.create_index(op.f('ix_conversations_last_inbound_message_at'), 'conversations', ['last_inbound_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_last_message_at'), 'conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('ix_conversations_organization_id'), 'conversations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_conversations_queued_at'), 'conversations', ['queued_at'], unique=False)
    op.create_index(op.f('ix_conversations_status'), 'conversations', ['status'], unique=False)
    op.create_index(op.f('ix_conversations_whatsapp_number_id'), 'conversations', ['whatsapp_number_id'], unique=False)
    op.create_index(op.f('ix_conversations_window_expires_at'), 'conversations', ['window_expires_at'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('whatsapp_number_id', sa.UUID(), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('sender_type', sa.String(length=50), nullable=False),
    sa.Column('sender_user_id', sa.UUID(), nullable=True),
    sa.Column('whatsapp_message_id', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_timestamp', sa.Integer(), nullable=True),
    sa.Column('message_type', sa.String(length=50), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('media_mime_type', sa.String(length=100), nullable=True),
    sa.Column('media_filename', sa.String(length=255), nullable=True),
    sa.Column('media_size_bytes', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='pending', nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('reply_to_message_id', sa.UUID(), nullable=True),
    sa.Column('is_internal_note', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reply_to_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['whatsapp_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['whatsapp_number_id'], ['whatsapp_numbers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_deleted_at'), 'messages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_messages_direction'), 'messages', ['direction'], unique=False)
    op.create_index(op.f('ix_messages_message_type'), 'messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_messages_organization_id'), 'messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_type'), 'messages', ['sender_type'], unique=False)
    op.create_index(op.f('ix_messages_sender_user_id'), 'messages', ['sender_user_id'], unique=False)
    op.create_index(op.f('ix_messages_status'), 'messages', ['status'], unique=False)
    op.create_index(op.f('ix_messages_whatsapp_message_id'), 'messages', ['whatsapp_message_id'], unique=True)
    op.create_index(op.f('ix_messages_whatsapp_number_id'), 'messages', ['whatsapp_number_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_whatsapp_number_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_whatsapp_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_status'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_organization_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_type'), table_name='messages')
    op.drop_index(op.f('ix_messages_direction'), table_name='messages')
    op.drop_index(op.f('ix_messages_deleted_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_window_expires_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_whatsapp_number_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_status'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_queued_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_organization_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_last_inbound_message_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_department_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_deleted_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_current_agent_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_contact_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_channel'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_active_chatbot_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_campaigns_whatsapp_number_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_template_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_scheduled_at'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_organization_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_name'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_deleted_at'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_created_by_user_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_created_at'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_campaign_type'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_index(op.f('ix_whatsapp_templates_whatsapp_number_id'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_status'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_organization_id'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_name'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_deleted_at'), table_name='whatsapp_templates')
    op.drop_index(op.f('ix_whatsapp_templates_created_at'), table_name='whatsapp_templates')
    op.drop_table('whatsapp_templates')
    op.drop_index(op.f('ix_nodes_organization_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_node_type'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_node_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_flow_id'), table_name='nodes')
    op.drop_index(op.f('ix_nodes_created_at'), table_name='nodes')
    op.drop_table('nodes')
    op.drop_table('contact_tags')
    op.drop_index(op.f('ix_whatsapp_numbers_phone_number'), table_name='whatsapp_numbers')
    op.drop_index(op.f('ix_whatsapp_numbers_organization_id'), table_name='whatsapp_numbers')
    op.drop_index(op.f('ix_whatsapp_numbers_deleted_at'), table_name='whatsapp_numbers')
    op.drop_index(op.f('ix_whatsapp_numbers_created_at'), table_name='whatsapp_numbers')
    op.drop_table('whatsapp_numbers')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_created_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_flows_organization_id'), table_name='flows')
    op.drop_index(op.f('ix_flows_deleted_at'), table_name='flows')
    op.drop_index(op.f('ix_flows_created_at'), table_name='flows')
    op.drop_index(op.f('ix_flows_chatbot_id'), table_name='flows')
    op.drop_table('flows')
    op.drop_index(op.f('ix_contacts_whatsapp_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_source'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_organization_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_name'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_lifecycle_stage'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_last_message_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_deleted_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_created_at'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_assigned_department_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_assigned_agent_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_index(op.f('ix_tags_organization_id'), table_name='tags')
    op.drop_index(op.f('ix_tags_name'), table_name='tags')
    op.drop_index(op.f('ix_tags_created_at'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_departments_slug'), table_name='departments')
    op.drop_index(op.f('ix_departments_organization_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_deleted_at'), table_name='departments')
    op.drop_index(op.f('ix_departments_created_at'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_chatbots_organization_id'), table_name='chatbots')
    op.drop_index(op.f('ix_chatbots_deleted_at'), table_name='chatbots')
    op.drop_index(op.f('ix_chatbots_created_at'), table_name='chatbots')
    op.drop_table('chatbots')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_plan_type'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_deleted_at'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_created_at'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
