"""Add conversation_states and conversation_logs tables for WhatsApp integration

Revision ID: 9f8e3d7c2b1a
Revises: ec7c4d8b9e1f
Create Date: 2025-12-12 20:56:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f8e3d7c2b1a'
down_revision: Union[str, None] = 'ec7c4d8b9e1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'conversation_states',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('phone_number', sa.String(length=20), nullable=False),
        sa.Column('flow_id', sa.UUID(), nullable=False),
        sa.Column('current_node_id', sa.String(length=255), nullable=True),
        sa.Column('variables', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
        sa.Column('execution_path', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
        sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('last_message_at', sa.DateTime(), nullable=True),
        sa.Column('session_expires_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_conv_expires', 'conversation_states', ['session_expires_at'], unique=False)
    op.create_index('idx_conv_org_flow_active', 'conversation_states', ['organization_id', 'flow_id', 'is_active'], unique=False)
    op.create_index('idx_conv_org_phone', 'conversation_states', ['organization_id', 'phone_number'], unique=False)
    op.create_index('idx_conversation_states_is_active', 'conversation_states', ['is_active'], unique=False)
    op.create_index('idx_conversation_states_phone_number', 'conversation_states', ['phone_number'], unique=False)
    
    op.create_table(
        'conversation_logs',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('organization_id', sa.UUID(), nullable=False),
        sa.Column('phone_number', sa.String(length=20), nullable=False),
        sa.Column('flow_id', sa.UUID(), nullable=False),
        sa.Column('user_message', sa.Text(), nullable=True),
        sa.Column('bot_response', sa.Text(), nullable=False),
        sa.Column('node_id', sa.String(length=255), nullable=True),
        sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
        sa.ForeignKeyConstraint(['flow_id'], ['flows.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_logs_org_flow_ts', 'conversation_logs', ['organization_id', 'flow_id', 'timestamp'], unique=False)
    op.create_index('idx_logs_org_phone_ts', 'conversation_logs', ['organization_id', 'phone_number', 'timestamp'], unique=False)
    op.create_index('idx_conversation_logs_phone_number', 'conversation_logs', ['phone_number'], unique=False)
    op.create_index('idx_conversation_logs_timestamp', 'conversation_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_conversation_logs_timestamp', table_name='conversation_logs')
    op.drop_index('idx_conversation_logs_phone_number', table_name='conversation_logs')
    op.drop_index('idx_logs_org_phone_ts', table_name='conversation_logs')
    op.drop_index('idx_logs_org_flow_ts', table_name='conversation_logs')
    op.drop_table('conversation_logs')
    
    op.drop_index('idx_conversation_states_phone_number', table_name='conversation_states')
    op.drop_index('idx_conversation_states_is_active', table_name='conversation_states')
    op.drop_index('idx_conv_org_phone', table_name='conversation_states')
    op.drop_index('idx_conv_org_flow_active', table_name='conversation_states')
    op.drop_index('idx_conv_expires', table_name='conversation_states')
    op.drop_table('conversation_states')
    # ### end Alembic commands ###
