"""adicionar status e connected_at ao whatsapp_numbers

Revision ID: ba3dfadb685d
Revises: flow_automation_schedule_001
Create Date: 2025-11-23 04:18:40.116620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3dfadb685d'
down_revision: Union[str, None] = 'flow_automation_schedule_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_flow_automation_schedule_exceptions_created_at'), 'flow_automation_schedule_exceptions', ['created_at'], unique=False)
    op.alter_column('flow_automation_schedules', 'recurrence_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.alter_column('flow_automation_schedules', 'execution_timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               nullable=True)
    op.alter_column('flow_automation_schedules', 'skip_weekends',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('flow_automation_schedules', 'skip_holidays',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('flow_automation_schedules', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('flow_automation_schedules', 'is_paused',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)
    op.alter_column('flow_automation_schedules', 'execution_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=True)
    op.create_index(op.f('ix_flow_automation_schedules_created_at'), 'flow_automation_schedules', ['created_at'], unique=False)
    op.create_index(op.f('ix_flow_automation_schedules_deleted_at'), 'flow_automation_schedules', ['deleted_at'], unique=False)
    op.add_column('whatsapp_numbers', sa.Column('status', sa.String(length=20), server_default='disconnected', nullable=False))
    op.add_column('whatsapp_numbers', sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('whatsapp_numbers', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whatsapp_numbers', 'last_seen_at')
    op.drop_column('whatsapp_numbers', 'connected_at')
    op.drop_column('whatsapp_numbers', 'status')
    op.drop_index(op.f('ix_flow_automation_schedules_deleted_at'), table_name='flow_automation_schedules')
    op.drop_index(op.f('ix_flow_automation_schedules_created_at'), table_name='flow_automation_schedules')
    op.alter_column('flow_automation_schedules', 'execution_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=False)
    op.alter_column('flow_automation_schedules', 'is_paused',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
    op.alter_column('flow_automation_schedules', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('flow_automation_schedules', 'skip_holidays',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('flow_automation_schedules', 'skip_weekends',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               nullable=False)
    op.alter_column('flow_automation_schedules', 'execution_timezone',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'America/Sao_Paulo'::character varying"),
               nullable=False)
    op.alter_column('flow_automation_schedules', 'recurrence_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'once'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_flow_automation_schedule_exceptions_created_at'), table_name='flow_automation_schedule_exceptions')
    # ### end Alembic commands ###
