# Generated by Django 6.0.1 on 2026-01-27 05:11

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('provider', models.CharField(choices=[('whatsapp', 'WhatsApp Business API'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('google_gemini', 'Google Gemini'), ('sendgrid', 'SendGrid Email'), ('twilio', 'Twilio SMS'), ('stripe', 'Stripe Payment')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('error', 'Error'), ('expired', 'Expired')], default='inactive', max_length=20)),
                ('api_key', models.TextField()),
                ('api_secret', models.TextField(blank=True, null=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('requests_today', models.IntegerField(default=0)),
                ('requests_limit', models.IntegerField(default=10000)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, null=True)),
                ('error_count', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integrations', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Integration Provider',
                'verbose_name_plural': 'Integration Providers',
                'db_table': 'integrations_provider',
            },
        ),
        migrations.CreateModel(
            name='IntegrationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('action', models.CharField(max_length=50)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error'), ('pending', 'Pending'), ('rate_limited', 'Rate Limited')], max_length=20)),
                ('response_time_ms', models.IntegerField(default=0)),
                ('request_body', models.JSONField(blank=True, default=dict)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='integrations.integrationprovider')),
            ],
            options={
                'verbose_name': 'Integration Log',
                'verbose_name_plural': 'Integration Logs',
                'db_table': 'integrations_log',
            },
        ),
        migrations.CreateModel(
            name='WebhookDestination',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('events', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('failed', 'Failed')], default='active', max_length=20)),
                ('secret_key', models.CharField(max_length=255)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('max_retries', models.IntegerField(default=5)),
                ('retry_interval_seconds', models.IntegerField(default=300)),
                ('total_delivered', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_destinations', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Webhook Destination',
                'verbose_name_plural': 'Webhook Destinations',
                'db_table': 'integrations_webhook_destination',
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('http_status_code', models.IntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='integrations.webhookdestination')),
            ],
            options={
                'verbose_name': 'Webhook Delivery Attempt',
                'verbose_name_plural': 'Webhook Delivery Attempts',
                'db_table': 'integrations_webhook_delivery_attempt',
            },
        ),
        migrations.AddIndex(
            model_name='integrationprovider',
            index=models.Index(fields=['organization', 'provider'], name='integration_organiz_8e4bc0_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationprovider',
            index=models.Index(fields=['status'], name='integration_status_41bf35_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationprovider',
            unique_together={('organization', 'provider')},
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['integration', 'created_at'], name='integration_integra_642264_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['status'], name='integration_status_11cf56_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationlog',
            index=models.Index(fields=['external_id'], name='integration_externa_c16e19_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdestination',
            index=models.Index(fields=['organization', 'status'], name='integration_organiz_67195d_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliveryattempt',
            index=models.Index(fields=['destination', 'status'], name='integration_destina_c92bda_idx'),
        ),
        migrations.AddIndex(
            model_name='webhookdeliveryattempt',
            index=models.Index(fields=['next_retry_at'], name='integration_next_re_689283_idx'),
        ),
    ]
