"""API v1 Endpoints Package"""

from . import (
    auth,
    organizations,
    users,
    contacts,
    conversations,
    whatsapp,
    chatbots,
    campaigns,
    analytics,
    queue,
    queues,
    departments,
    ai_assistant,
    agent_skills,
    secrets,
    database,
    websocket,
    debug,
    flow_automations,
)

__all__ = [
    "auth",
    "organizations",
    "users",
    "contacts",
    "conversations",
    "whatsapp",
    "chatbots",
    "campaigns",
    "analytics",
    "queue",
    "queues",
    "departments",
    "ai_assistant",
    "agent_skills",
    "secrets",
    "database",
    "websocket",
    "debug",
    "flow_automations",
]
