# Generated by Django 6.0.1 on 2026-01-27 04:14

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('whatsapp_business_id', models.CharField(blank=True, max_length=255, null=True)),
                ('whatsapp_webhook_verify_token', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_type', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], db_index=True, default='free', max_length=50)),
                ('plan_starts_at', models.DateTimeField(blank=True, null=True)),
                ('plan_expires_at', models.DateTimeField(blank=True, null=True)),
                ('max_chatbots', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_whatsapp_numbers', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_contacts', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_agents', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_departments', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('monthly_message_limit', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_chatbots_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_whatsapp_numbers_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_contacts_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_agents_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_month_messages_sent', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('current_month_messages_received', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('settings', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('is_trial', models.BooleanField(default=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'organizations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['slug'], name='organizatio_slug_5b8b37_idx'), models.Index(fields=['plan_type'], name='organizatio_plan_ty_5a2a35_idx'), models.Index(fields=['is_active'], name='organizatio_is_acti_bdc355_idx')],
            },
        ),
    ]
